name: build-release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |  
          sudo apt-get update
          sudo apt-get install -y python3 curl
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
          export PATH=$PATH:~/.platformio/penv/bin
          platformio run
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .pio/build/bluepill_f103c8/firmware.elf
            LICENSE
